package models

var CAS_REGIONS = map[string]string{
	"cn-qingdao":            "cas.aliyuncs.com",
	"cn-beijing":            "cas.aliyuncs.com",
	"cn-zhangjiakou":        "cas.aliyuncs.com",
	"cn-huhehaote":          "cas.aliyuncs.com",
	"cn-hangzhou":           "cas.aliyuncs.com",
	"cn-shanghai":           "cas.aliyuncs.com",
	"cn-shenzhen":           "cas.aliyuncs.com",
	"cn-chengdu":            "cas.aliyuncs.com",
	"cn-hongkong":           "cas.aliyuncs.com",
	"ap-northeast-1":        "cas.ap-northeast-1.aliyuncs.com",
	"ap-southeast-1":        "cas.aliyuncs.com",
	"ap-southeast-2":        "cas.ap-southeast-2.aliyuncs.com",
	"ap-southeast-3":        "cas.aliyuncs.com",
	"ap-southeast-5":        "cas.aliyuncs.com",
	"us-east-1":             "cas.aliyuncs.com",
	"us-west-1":             "cas.aliyuncs.com",
	"eu-west-1":             "cas.aliyuncs.com",
	"eu-central-1":          "cas.eu-central-1.aliyuncs.com",
	"ap-south-1":            "cas.ap-south-1.aliyuncs.com",
	"me-east-1":             "cas.me-east-1.aliyuncs.com",
	"cn-hangzhou-finance":   "cas.aliyuncs.com",
	"cn-shanghai-finance-1": "cas.aliyuncs.com",
	"cn-shenzhen-finance-1": "cas.aliyuncs.com",
	"cn-beijing-finance-1":  "cas.aliyuncs.com",
}
